#!/bin/sh
# ==============================================================================
# TaiXu (LinuxAIRuntime) - Flutter Project One-Key Build Engine
# Usage: build_flutter.sh <project_path> [target]
# ==============================================================================
set -e

PROJECT_PATH="${1:-.}"
TARGET="${2:-apk --debug}"
GRADLE_VER="8.14.2"

echo "==> [TaiXu Build Engine] 启动 Flutter 项目跨端编译..."
echo "==> [TaiXu Build] 项目路径: $PROJECT_PATH"

# 1. 注入 Flutter 与 Gradle PATH (优先加载插件装配期固化的环境变量)
if [ -f /etc/profile.d/taixu-android.sh ]; then
    . /etc/profile.d/taixu-android.sh
fi
export PATH="/opt/flutter/bin:/opt/gradle-8.14.2/bin:/opt/gradle-8.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
export ANDROID_HOME="${ANDROID_HOME:-/opt/android-sdk}"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PUB_HOSTED_URL="https://pub.flutter-io.cn"
export FLUTTER_STORAGE_BASE_URL="https://storage.flutter-io.cn"
export PUB_CACHE="${PUB_CACHE:-/opt/taixu/cache/flutter-pub}"

# Wire the native ARM64 llvm-strip into every installed NDK. AGP derives the
# executable path from the NDK host tag (linux-x86_64), even on ARM64; a small
# shell shim at that path lets it invoke the real ARM64 LLVM binary.
LLVM_STRIP="${TAIXU_LLVM_STRIP_PATH:-/opt/taixu/android-sdk-tools/llvm/llvm-strip}"
if [ ! -x "$LLVM_STRIP" ]; then
    LLVM_STRIP="$(command -v llvm-strip 2>/dev/null || true)"
fi
if [ -z "$LLVM_STRIP" ] || [ ! -x "$LLVM_STRIP" ]; then
    echo "==> [TaiXu Build] 正在补装 ARM64 llvm-strip..."
    (DEBIAN_FRONTEND=noninteractive apt-get update -y >/dev/null 2>&1 && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends llvm >/dev/null 2>&1) || true
    LLVM_STRIP="$(command -v llvm-strip 2>/dev/null || true)"
fi
if [ -z "$LLVM_STRIP" ] || [ ! -x "$LLVM_STRIP" ]; then
    echo "==> [TaiXu Build] ❌ 未找到可执行的 ARM64 llvm-strip，拒绝生成带完整调试符号的超大 APK"
    exit 126
fi
LLVM_STRIP="$(readlink -f "$LLVM_STRIP" 2>/dev/null || echo "$LLVM_STRIP")"
mkdir -p /opt/taixu/android-sdk-tools/llvm
ln -sf "$LLVM_STRIP" /opt/taixu/android-sdk-tools/llvm/llvm-strip
LLVM_STRIP=/opt/taixu/android-sdk-tools/llvm/llvm-strip
for ndk_dir in "$ANDROID_HOME"/ndk/*; do
    [ -d "$ndk_dir" ] || continue
    ndk_strip_dir="$ndk_dir/toolchains/llvm/prebuilt/linux-x86_64/bin"
    mkdir -p "$ndk_strip_dir"
    ndk_strip="$ndk_strip_dir/llvm-strip"
    if [ ! -x "$ndk_strip" ] || [ "$(readlink "$ndk_strip" 2>/dev/null || true)" != "$LLVM_STRIP" ]; then
        rm -f "$ndk_strip"
        ln -sf "$LLVM_STRIP" "$ndk_strip"
    fi
done
export TAIXU_LLVM_STRIP_PATH="$LLVM_STRIP"
echo "==> [TaiXu Build] 使用 ARM64 llvm-strip: $LLVM_STRIP"

# 2. 自愈软链接
if [ -d /opt/flutter/bin ] && [ ! -f /usr/local/bin/flutter ]; then
    ln -sf /opt/flutter/bin/flutter /usr/local/bin/flutter 2>/dev/null || true
    ln -sf /opt/flutter/bin/dart /usr/local/bin/dart 2>/dev/null || true
fi

cd "$PROJECT_PATH"

if ! command -v flutter >/dev/null 2>&1; then
    echo "==> [TaiXu Build] ❌ 未找到 Flutter SDK，请安装 Flutter 跨平台开发套件"
    exit 127
fi
if [ ! -f /opt/flutter/.taixu-arm64 ] || [ ! -x /opt/flutter/bin/cache/dart-sdk/bin/dart ]; then
    echo "==> [TaiXu Build] ❌ Flutter SDK 不是可用的 Linux ARM64 版本，请在工坊重新装配 Flutter 套件"
    exit 126
fi
if [ ! -f "${ANDROID_HOME}/platforms/android-34/android.jar" ]; then
    echo "==> [TaiXu Build] ❌ 缺少 Android SDK Platform 34，请同时安装 Android 核心基础环境"
    exit 126
fi
if [ ! -x "${ANDROID_HOME}/build-tools/34.0.0/aapt2" ]; then
    echo "==> [TaiXu Build] ❌ 缺少 Android Build-Tools 34，请重新装配 Android 核心基础环境"
    exit 126
fi

# Migrate projects generated by the previous TaiXu Flutter template. That
# template disabled stripping for every .so to bypass the x86_64 NDK tool,
# which could inflate a debug APK beyond 1 GB. Only remove the exact managed
# block; user-defined, selective keepDebugSymbols rules are left untouched.
FLUTTER_APP_GRADLE="android/app/build.gradle"
if [ -f "$FLUTTER_APP_GRADLE" ] && grep -Fq 'keepDebugSymbols += "**/*.so"' "$FLUTTER_APP_GRADLE"; then
    python3 - "$FLUTTER_APP_GRADLE" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
managed_block = '''    // NDK 只提供 linux-x86_64 的 llvm-strip，在 ARM64 PRoot 里无法启动。
    // 保留 native 调试符号，避免 AGP 调用它导致构建失败。
    packaging {
        jniLibs {
            keepDebugSymbols += "**/*.so"
        }
    }

'''
if managed_block in text:
    path.write_text(text.replace(managed_block, "", 1), encoding="utf-8")
    print("==> [TaiXu Build] 已迁移旧版 Flutter 模板：启用 native 符号剥离")
PY
    if grep -Fq 'keepDebugSymbols += "**/*.so"' "$FLUTTER_APP_GRADLE"; then
        echo "==> [TaiXu Build] ❌ 检测到全量 keepDebugSymbols 配置，请删除后重试"
        exit 126
    fi
fi

mkdir -p "$PUB_CACHE" android
if [ -f /opt/flutter/bin/flutter ]; then
    printf 'sdk.dir=%s\nflutter.sdk=/opt/flutter\n' "$ANDROID_HOME" > android/local.properties
fi
AAPT2_PATH="${TAIXU_AAPT2_PATH:-}"
if [ -z "$AAPT2_PATH" ] || [ ! -x "$AAPT2_PATH" ]; then
    for candidate in \
        "/opt/taixu/android-sdk-tools/aapt2" \
        "/opt/taixu/android-sdk-tools/35.0.2/build-tools/aapt2" \
        "/usr/local/bin/aapt2" \
        "/usr/bin/aapt2"; do
        if [ -x "$candidate" ]; then
            AAPT2_PATH="$candidate"
            break
        fi
    done
    if [ -n "$AAPT2_PATH" ] && [ -x "$AAPT2_PATH" ]; then
        export ORG_GRADLE_PROJECT_android_aapt2FromMavenOverride="$AAPT2_PATH"
        echo "==> [TaiXu Build] 使用 ARM64 原生 AAPT2: $AAPT2_PATH"
    fi
elif [ -x "$AAPT2_PATH" ]; then
    export ORG_GRADLE_PROJECT_android_aapt2FromMavenOverride="$AAPT2_PATH"
    echo "==> [TaiXu Build] 使用 ARM64 原生 AAPT2: $AAPT2_PATH"
fi

export GRADLE_OPTS="${GRADLE_OPTS:-} -Dorg.gradle.jvmargs=-Xmx1024m"

echo "==> [TaiXu Build] 正在拉取 Flutter 依赖 (flutter pub get)..."
flutter pub get

# 3. 确保 Android 宿主使用本地 Gradle 8.14.2 + 国内镜像，避免 Wrapper 从 services.gradle.org
#    下载发行版（国内网络易被重置，报 SocketException: connection abort）。
mkdir -p android/gradle/wrapper
cat > android/gradle/wrapper/gradle-wrapper.properties <<'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://mirrors.cloud.tencent.com/gradle/gradle-8.14.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
cat > android/gradlew <<'EOF'
#!/bin/sh
# 优先复用插件装配期已装好的本地 Gradle 8.14.2，避免 Wrapper 重新下载发行版。
DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -x /opt/gradle-8.14.2/bin/gradle ]; then
    exec /opt/gradle-8.14.2/bin/gradle "$@"
elif [ -x /opt/gradle-8.7/bin/gradle ]; then
    exec /opt/gradle-8.7/bin/gradle "$@"
elif [ -f "$DIR/gradle/wrapper/gradle-wrapper.jar" ]; then
    exec java -jar "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
elif [ -x /usr/local/bin/gradle ]; then
    exec /usr/local/bin/gradle "$@"
elif command -v gradle >/dev/null 2>&1; then
    exec gradle "$@"
else
    exec /usr/bin/gradle "$@"
fi
EOF
chmod +x android/gradlew

# 4. 全局强制阿里云镜像：Flutter 每次会重写工程文件，这里兜底写入全局 init 脚本，
#    并把 GRADLE_USER_HOME 固定到 /root/.gradle，确保依赖解析一定走国内源。
export GRADLE_USER_HOME="/root/.gradle"
mkdir -p "$GRADLE_USER_HOME"
cat > "$GRADLE_USER_HOME/init.gradle" <<'EOF'
// TaiXu: 全局强制阿里云镜像。
gradle.beforeSettings { settings ->
    settings.pluginManagement.repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    settings.dependencyResolutionManagement.repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://storage.flutter-io.cn/download.flutter.io' }
        google()
        mavenCentral()
    }
}
EOF

echo "==> [TaiXu Build] 正在执行 Flutter 打包编译 (flutter build $TARGET)..."
exec flutter build $TARGET
